dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo

  provider:
    timeout: 1000
    UserService:
      version: 1.0.0